/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.korisnik;

import domain.Korisnik;
import domain.Pivo;
import domain.Recenzija;
import java.awt.Color;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import service.KorisnikService;

/**
 *
 * @author milos
 */
public class DodajRecenzijuForm extends javax.swing.JDialog {

    private int selektovanaOcena = 0;
    /**
     * Creates new form DodajRecenzijuForm
     */
    public DodajRecenzijuForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicijalizujLabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDodajRecenziju = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRecenzijaPiva = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabelImeKorisnika = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelNazivPiva = new javax.swing.JLabel();
        jButtonOcena1 = new javax.swing.JButton();
        jButtonOcena2 = new javax.swing.JButton();
        jButtonOcena3 = new javax.swing.JButton();
        jButtonOcena4 = new javax.swing.JButton();
        jButtonOcena5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Recenzija:");

        jLabel1.setText("Naziv Piva: ");

        jButtonDodajRecenziju.setText("Dodaj Recenziju");
        jButtonDodajRecenziju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajRecenzijuActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jTextAreaRecenzijaPiva.setColumns(20);
        jTextAreaRecenzijaPiva.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRecenzijaPiva);

        jLabel5.setText("Ocena: ");

        jLabelImeKorisnika.setText("Ime Korisnika");

        jLabel10.setText("Korisnik: ");

        jLabelNazivPiva.setText("Naziv Piva");

        jButtonOcena1.setText("1");
        jButtonOcena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcena1ActionPerformed(evt);
            }
        });

        jButtonOcena2.setText("2");
        jButtonOcena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcena2ActionPerformed(evt);
            }
        });

        jButtonOcena3.setText("3");
        jButtonOcena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcena3ActionPerformed(evt);
            }
        });

        jButtonOcena4.setText("4");
        jButtonOcena4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcena4ActionPerformed(evt);
            }
        });

        jButtonOcena5.setText("5");
        jButtonOcena5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcena5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOcena1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOcena2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOcena3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOcena4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOcena5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOdustani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDodajRecenziju))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNazivPiva))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelImeKorisnika)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNazivPiva))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelImeKorisnika))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonOcena1)
                    .addComponent(jButtonOcena2)
                    .addComponent(jButtonOcena3)
                    .addComponent(jButtonOcena4)
                    .addComponent(jButtonOcena5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonDodajRecenziju))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDodajRecenzijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajRecenzijuActionPerformed
        String tekst = jTextAreaRecenzijaPiva.getText().trim();
        
        //Validacija unosa
        if (tekst.isEmpty() || selektovanaOcena == 0) {
            JOptionPane.showMessageDialog(this, "Unesite ocenu i tekst recenzije.");
            return;
        }

        //Nova recenzija
        Recenzija nova = new Recenzija();
        nova.setKorisnikID(KorisnikService.getInstance().getUlogovaniKorisnik().getKorisnikID());
        nova.setPivoID(KorisnikService.getInstance().getSelektovanoPivo().getPivoID());
        nova.setSadrzaj(tekst);
        nova.setOcena(selektovanaOcena);
        nova.setDatumKreiranja(new Date());

        try {
            KorisnikService.getInstance().addRecenzija(nova);
            JOptionPane.showMessageDialog(this, "Recenzija uspešno dodata.");
            KorisnikService.getInstance().getPanelRecenzije().prikaziDetaljePiva(KorisnikService.getInstance().getSelektovanoPivo());
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greška prilikom dodavanja.");
        }
    }//GEN-LAST:event_jButtonDodajRecenzijuActionPerformed

    private void jButtonOcena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcena1ActionPerformed
        selektovanaOcena = 1;
        osveziBojeOcena();
    }//GEN-LAST:event_jButtonOcena1ActionPerformed

    private void jButtonOcena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcena2ActionPerformed
        selektovanaOcena = 2;
        osveziBojeOcena();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOcena2ActionPerformed

    private void jButtonOcena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcena3ActionPerformed
        selektovanaOcena = 3;
        osveziBojeOcena();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOcena3ActionPerformed

    private void jButtonOcena4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcena4ActionPerformed
        selektovanaOcena = 4;
        osveziBojeOcena();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOcena4ActionPerformed

    private void jButtonOcena5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcena5ActionPerformed
        selektovanaOcena = 5;
        osveziBojeOcena();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOcena5ActionPerformed

    private void osveziBojeOcena() {
        JButton[] dugmici = {jButtonOcena1, jButtonOcena2, jButtonOcena3, jButtonOcena4, jButtonOcena5};
        for (int i = 0; i < dugmici.length; i++) {
            if (i + 1 == selektovanaOcena) {
                dugmici[i].setBackground(Color.ORANGE);
            } else {
                dugmici[i].setBackground(null);
            }
        }
    }
    
    private void inicijalizujLabele() {
        Pivo pivo = KorisnikService.getInstance().getSelektovanoPivo();
        Korisnik korisnik = KorisnikService.getInstance().getUlogovaniKorisnik();
        jLabelNazivPiva.setText(pivo.getNaziv());
        jLabelImeKorisnika.setText(korisnik.getIme() + " " + korisnik.getPrezime());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajRecenziju;
    private javax.swing.JButton jButtonOcena1;
    private javax.swing.JButton jButtonOcena2;
    private javax.swing.JButton jButtonOcena3;
    private javax.swing.JButton jButtonOcena4;
    private javax.swing.JButton jButtonOcena5;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelImeKorisnika;
    private javax.swing.JLabel jLabelNazivPiva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRecenzijaPiva;
    // End of variables declaration//GEN-END:variables
}
