/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.pivara;

import service.PivaraService;
import forms.pivara.PanelNalogPivara;
import forms.pivara.PanelPiva;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author milos
 */
public class PivaraMainForm extends javax.swing.JFrame {

    /**
     * Creates new form PivaraMainForm
     */
    public PivaraMainForm() {
        initComponents();
        setLocationRelativeTo(null);
        inicijalizujFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovanaPivara = new javax.swing.JLabel();
        jButtonPiva = new javax.swing.JButton();
        jButtonNalog = new javax.swing.JButton();
        jButtonIzadji = new javax.swing.JButton();
        jButtonOsvezi = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUlogovanaPivara.setText("jLabel1");

        jButtonPiva.setBackground(new java.awt.Color(242, 242, 242));
        jButtonPiva.setText("Piva");
        jButtonPiva.setBorderPainted(false);
        jButtonPiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPivaActionPerformed(evt);
            }
        });

        jButtonNalog.setBackground(new java.awt.Color(242, 242, 242));
        jButtonNalog.setText("Nalog");
        jButtonNalog.setBorderPainted(false);
        jButtonNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNalogActionPerformed(evt);
            }
        });

        jButtonIzadji.setBackground(new java.awt.Color(255, 150, 150));
        jButtonIzadji.setText("Izadji");
        jButtonIzadji.setBorderPainted(false);
        jButtonIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzadjiActionPerformed(evt);
            }
        });

        jButtonOsvezi.setBackground(new java.awt.Color(242, 242, 242));
        jButtonOsvezi.setText("Osvezi");
        jButtonOsvezi.setBorderPainted(false);
        jButtonOsvezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsveziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIzadji, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jButtonOsvezi, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jButtonPiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelUlogovanaPivara, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelUlogovanaPivara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNalog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOsvezi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIzadji))
                    .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPivaActionPerformed
        PanelPiva panel = PivaraService.getInstance().getPanelPiva();
        prikaziPanel(panel);
    }//GEN-LAST:event_jButtonPivaActionPerformed

    private void jButtonNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNalogActionPerformed
        PanelNalogPivara panel = PivaraService.getInstance().getPanelNalogPivara();
        prikaziPanel(panel);
    }//GEN-LAST:event_jButtonNalogActionPerformed

    private void jButtonIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzadjiActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonIzadjiActionPerformed

    private void jButtonOsveziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsveziActionPerformed
        try {
            service.PivaraService.getInstance().osveziDugme();
        } catch (Exception ex) {
            Logger.getLogger(PivaraMainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOsveziActionPerformed

    private void prikaziPanel(javax.swing.JPanel panel) {
        jPanelMain.removeAll();
        jPanelMain.setLayout(new java.awt.BorderLayout());
        jPanelMain.add(panel, java.awt.BorderLayout.CENTER);
        jPanelMain.revalidate();
        jPanelMain.repaint();
    }

    private void inicijalizujFormu() {
        try {
            PivaraService service = PivaraService.getInstance();
            service.inicijalnoUcitavanje();
            service.kreirajPanele();
            jLabelUlogovanaPivara.setText(service.getUlogovanaPivara().getNaziv());
            prikaziPanel(service.getPanelNalogPivara());
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzadji;
    private javax.swing.JButton jButtonNalog;
    private javax.swing.JButton jButtonOsvezi;
    private javax.swing.JButton jButtonPiva;
    private javax.swing.JLabel jLabelUlogovanaPivara;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
